export enum Admin {
    ADD_MOVIE_RECORDS = "ADD_MOVIE_RECORDS",
    ADD_MOVIE_RECORDS_SUCCESS = "ADD_MOVIE_RECORDS_SUCCESS",
    ADD_MOVIE_RECORDS_FAIL = "ADD_MOVIE_RECORDS_FAIL",
    GET_ALL_MOVIE_RECORDS_ADMIN = "GET_ALL_MOVIE_RECORDS_ADMIN",
    GET_ALL_MOVIE_RECORDS_ADMIN_SUCCESS = "GET_ALL_MOVIE_RECORDS_ADMIN_SUCCESS",
    GET_ALL_MOVIE_RECORDS_ADMIN_FAIL = "GET_ALL_MOVIE_RECORDS_ADMIN_FAIL",
  }