export enum AppSidebar {
    GET_CONVERSATION_LIST_BY_USER = "GET_CHAT_LIST_BY_USER",
    GET_CONVERSATION_LIST_BY_USER_SUCCESS = "GET_CHAT_LIST_BY_USER_SUCCESS",
    GET_CONVERSATION_LIST_BY_USER_FAIL = "GET_CHAT_LIST_BY_USER_FAIL",
}