export enum ChatWindow {
    GET_ALL_CHAT_MESSAGES = "GET_ALL_CHAT_MESSAGES",
    GET_ALL_CHAT_MESSAGES_SUCCESS = "GET_ALL_CHAT_MESSAGES_SUCCESS",
    GET_ALL_CHAT_MESSAGES_FAIL = "GET_ALL_CHAT_MESSAGES_FAIL",
    GET_USER_QUERY_RESPONSE_CHAT_WINDOW = "GET_USER_QUERY_RESPONSE_CHAT_WINDOW",
    GET_USER_QUERY_RESPONSE_SUCCESS_CHAT_WINDOW = "GET_USER_QUERY_RESPONSE_SUCCESS_CHAT_WINDOW",
    GET_USER_QUERY_RESPONSE_FAIL_CHAT_WINDOW = "GET_USER_QUERY_RESPONSE_FAIL_CHAT_WINDOW"
}
