export enum Dashboard {
    GET_PROJECT_TASKS = "GET_PROJECT_TASKS",
    GET_PROJECT_TASKS_SUCCESS = "GET_PROJECT_TASKS_SUCCESS",
    GET_PROJECT_TASKS_FAIL = "GET_PROJECT_TASKS_FAIL",
    GET_EMPLOYEE_INFO = "GET_EMPLOYEE_INFO",
    GET_EMPLOYEE_INFO_SUCCESS = "GET_EMPLOYEE_INFO_SUCCESS",
    GET_EMPLOYEE_INFO_FAIL = "GET_EMPLOYEE_INFO_FAIL"
}