export enum Home {
    SET_INIT_USER_QUERY = "SET_INIT_USER_QUERY",
    SET_USER_QUERY = "SET_USER_QUERY",
    SET_USER_QUERY_SUCCESS = "SET_USER_QUERY_SUCCESS",
    SET_USER_QUERY_FAIL = "SET_USER_QUERY_FAIL",
    GET_USER_LOGIN_INFO = "GET_USER_LOGIN_INFO",
    GET_USER_LOGIN_INFO_SUCCESS = "GET_USER_LOGIN_INFO_SUCCESS",
    GET_USER_LOGIN_INFO_FAIL = "GET_USER_LOGIN_INFO_FAIL"
}
