export enum Home {
    SET_INIT_USER_QUERY = "SET_INIT_USER_QUERY",
    SET_USER_QUERY = "SET_USER_QUERY",
    SET_USER_QUERY_SUCCESS = "SET_USER_QUERY_SUCCESS",
    SET_USER_QUERY_FAIL = "SET_USER_QUERY_FAIL"
}
