export enum Login {
    LOG_USER_CREDNTIALS = "ADD_USER_CREDNTIALS",
    LOG_USER_CREDNTIALS_SUCCESS = "ADD_USER_CREDNTIALS_SUCCESS",
    LOG_USER_CREDNTIALS_FAIL = "ADD_USER_CREDNTIALS_FAIL",
    LOG_OUT_USER = "LOG_OUT_USER",
}