export enum OAuth {
    GET_AUTHORIZATION_URL="GET_AUTHORIZATION_CODE",
    GET_AUTHORIZATION_URL_SUCCESS="GET_AUTHORIZATION_CODE_SUCCESS",
    GET_AUTHORIZATION_URL_FAIL="GET_AUTHORIZATION_CODE_FAIL",
    SET_AUTHORIZATION_CODE="SET_AUTHORIZATION_CODE",
    SET_AUTHORIZATION_CODE_SUCCESS="SET_AUTHORIZATION_CODE_SUCCESS",
    SET_AUTHORIZATION_CODE_FAIL="SET_AUTHORIZATION_CODE_FAIL"
  }