export enum SeatPlan {
    GET_SELECTED_MOVIE = "GET_SELECTED_MOVIE_IN_SEAT_PLAN",
    GET_SELECTED_MOVIE_SUCCESS = "GET_SELECTED_MOVIE_SUCCESS_IN_SEAT_PLAN",
    GET_SELECTED_MOVIE_FAIL = "GET_SELECTED_MOVIE_FAIL_IN_SEAT_PLAN",
    GET_SELECTED_THEATER = "GET_SELECTED_THEATER",
    GET_SELECTED_THEATER_SUCCESS = "GET_SELECTED_THEATER_SUCCESS",
    GET_SELECTED_THEATER_FAIL = "GET_SELECTED_THEATER_FAIL",
    SET_SEAT_IDS = "SET_SEAT_IDS",
    ADD_BOOKING_INFO = "ADD_BOOKING_INFO",
    ADD_BOOKING_INFO_SUCCESS = "ADD_BOOKING_INFO_SUCCESS",
    ADD_BOOKING_INFO_FAIL = "ADD_BOOKING_INFO_FAIL",
    DELETE_BOOKING_INFO = "DELETE_BOOKING_INFO",
    DELETE_BOOKING_INFO_SUCCESS = "DELETE_BOOKING_INFO_SUCCESS",
    DELETE_BOOKING_INFO_FAIL = "DELETE_BOOKING_INFO_FAIL",
    GET_RESERVED_SEATS_IDS = "GET_RESERVED_SEATS_IDS",
    GET_RESERVED_SEATS_IDS_SUCCESS = "GET_RESERVED_SEATS_IDS_SUCCESS",
    GET_RESERVED_SEATS_IDS_FAIL = "GET_RESERVED_SEATS_IDS_FAIL",
    GET_PERMANENTLY_RESERVED_SEATS_IDS = "GET_PERMANENTLY_RESERVED_SEATS_IDS",
    GET_PERMANENTLY_RESERVED_SEATS_IDS_SUCCESS = "GET_PERMANENTLY_RESERVED_SEATS_IDS_SUCCESS",
    GET_PERMANENTLY_RESERVED_SEATS_IDS_FAIL = "GET_PERMANENTLY_RESERVED_SEATS_IDS_FAIL",
    ADD_CLAIMS_TO_TOKEN = "ADD_CLAIMS_TO_TOKEN_IN_SEAT_PLAN",
    ADD_CLAIMS_TO_TOKEN_SUCCESS = "ADD_CLAIMS_TO_TOKEN_SUCCESS_IN_SEAT_PLAN",
    ADD_CLAIMS_TO_TOKEN_FAIL = "ADD_CLAIMS_TO_TOKEN_FAIL_IN_SEAT_PLAN"
  }

  